server:
  port: 10086
spring:
  application:
    name: ly-registry
eureka:
  client:
    register-with-eureka: false #不用在eureka中注册自己
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:10086/eureka