server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka: #注册到eureka
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
zuul:
  prefix: /api #添加路由前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/** # 搜索微服务
    user-service: /user/** # 用户微服务
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** # 购物车微服务
    order-manage: /order/** # 订单微服务
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  sensitive-headers:
  add-host-header: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMiilseconds: 5000 #熔断超时时长：5000ms
ribbon:
  ConnectTimeout: 1000 #ribbon 链接超时时长
  ReadTimeout: 3500 #ribbon读取超时时长
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数
ly:
  jwt:
    pubKeyPath: C://tmp/rsa/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/user/send
      - /api/item
      - /api/upload