server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/market?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 192.168.164.128
  rabbitmq:
    username: root
    password: 123456
    virtual-host: /ly
    host: 149.129.67.59
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  type-aliases-package: com.ly.user.pojo